newsite/clubsite/urls.py
from django.urls import path
from . import views

app_name = 'newsite'
urlpatterns = [
  path('home', views.home, name = 'home'),
  path('members', views.members, name = 'members'),
  path('id/<int:id>', views.id, name = 'id'),
]

newsite/newsite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/', include('clubsite.urls')),
]

newsite/clubsite/views.py
from django.shortcuts import render


class Member:
    def __init__(self, id, name, join_at, picture_path):
        self.id = id
        self.name = name
        self.join_at = join_at
        self.picture_path = picture_path

member_list = [
  Member(0,'taro','2018/04/01', 'img/taro.jpg'),
  Member(1, 'jiro', '2019/04/01', 'img/jiro.jpg'),
  Member(2, 'hanako', '2019/05/02', 'img/hanako.jpg'),
  Member(3, 'yoshiko', '2018/10/01', 'img/yoshiko.jpg')
]
# Create your views here.
def home(request):
    return render(request, 'home.html')


def members(request):
    return render(request, 'members.html', context = {
      'members': member_list
    })


def id(request, id):
    return render(request, 'id.html', context = {
      'member': member_list[id]
    })

newsite/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset='utf-8'>
    <title>{% block title %}Django大学{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="{% url 'newsite:home' %}">Home</a>
      <a class="navbar-brand" href="{% url 'newsite:members' %}">メンバー</a>
    </nav>
    {% block content %}{% endblock %}
  </body>

newsite/templates/home.html
{% extends "base.html" %}
{% block title %}ホーム{{ block.super }}{% endblock %}
{% block content %}
<p>django 大学<p>
{% endblock %}

newsite/templates/id.html
{% extends "base.html" %}
{% block title %}詳細{{ block.super }}{% endblock %}
{% block content %}
{% load static %}

<h1>メンバー詳細</h1>
<img src="{% static member.picture_path %}">
<p>名前: {{ member.name }}</p>
<p>入部日: {{member.join_at}}</p>
<p>入部から: {{ member.join_at|culcurate_datetime_to_now }}</p>
{% endblock %}

newsite/templates/members.html
{% extends "base.html" %}
{% block title %}メンバー一覧{{ block.super }}{% endblock %}
{% block content %}
{% for member in members %}
  <p><a href="{% url 'newsite:id' id=member.id %}">{{ member.name }}</p>
{% endfor %}
{% endblock %}